language: c
before_install:
    - sudo apt-get update
    - sudo apt-get install -y check
compiler: 
    - gcc
scripts:
    - make Makefile
    - gcc -Wall -o spell_check dictionary.o spell.o main.o
    - ./spell_check test1.txt wordlist.txt